(in-package :mu-cl-resources)

(define-resource resource1 ()
  :class (s-prefix "push:Resource1")
  :properties `((:title :string ,(s-prefix "dct:title"))
                (:num :number ,(s-prefix "push:number")))
  :has-many `((resource2 :via ,(s-prefix "push:resources2")
                         :as "resources2"))
  :resource-base (s-url "http://mu.semte.ch/test/resources/resource1/")
  :on-path "resource1")

(define-resource resource2 ()
  :class (s-prefix "push:Resource2")
  :properties `((:title :string ,(s-prefix "dct:title"))
                (:num :number ,(s-prefix "push:number")))
  :has-one `((resource1 :via ,(s-prefix "push:resource1")
                        :as "resources1"))
  :resource-base (s-url "http://mu.semte.ch/test/resources/resource2/")
  :on-path "resource2")
